import Head from "next/head";
import Image from "next/image";
import Contact from "../components/Contact";
import Hero from "../components/Hero";
import Instagram from "../components/Instagram";
import Slider from "../components/Slider";
import {SliderData} from "../components/SliderData";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Xelvis64</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero heading="Xelvis64" message="A little team with a big dream." />
      <Slider slides={SliderData} />
      <Instagram />
      <Contact />
    </div>
  );
}
